---
output: html_document
---

# Instructions

**1)** Install the `palmerpenguins` R Package

**2)** Create a new R Markdown document (`.rmd`)

**3)** Write a **YAML** header including the document title, the authors, the date, and output formats html, pdf and word with a table of content for each

**4)** Include a single section (level 1) and two subsections (level 2)

**5)** In the first subsection:

  - Add paragraphs including normal and formatted text (italic, bold)

  - Add artwork from @allison_horst on palmer penguins found on the `palmerpenguins` R Package GitHub repository (https://github.com/allisonhorst/palmerpenguins) as a local image (for pdf output).

  - Add a footnote to the artwork that states: *"Artwork by @allison_horst"*

  - Add a code chunk that loads the `palmerpenguins` package and `penguins` dataset. Generate a table with to visualize the first 20 lines of the dataset.

**6)** In the second subsection:

  - Copy the following text and use inline code chunks to fill in the blanks:

    > The penguins dataset contains data on \_\_\_\_ individuals, \_\_\_\_ species, and from \_\_\_\_ islands. Across individuals, the mean flipper length is \_\_\_\_.

  - In the previous text, add a hyperlink to the `palmerpenguins` R Package GitHub repository when a user clicks on [penguins dataset](https://github.com/allisonhorst/palmerpenguins);

  - Add a code chunk that generates a scatterplot of flipper length on the x-axis and body mass on the y-axis.

**7)** Render `.html`, `.pdf` and `.docx` documents.
